// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdKxOVOLhqByLTbTQQxW8Ae3m8hELBu-Q',
    appId: '1:527002016051:web:5494599dbdb4f4dc23c646',
    messagingSenderId: '527002016051',
    projectId: 'elevate-988ab',
    authDomain: 'elevate-988ab.firebaseapp.com',
    storageBucket: 'elevate-988ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70-cK8XdfP-XLNVmCpABfm2W0CnBzWjg',
    appId: '1:527002016051:android:fdb70e17995382f523c646',
    messagingSenderId: '527002016051',
    projectId: 'elevate-988ab',
    storageBucket: 'elevate-988ab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5KoAdaag1WZcFPsulPMHpNtu0CFAI58U',
    appId: '1:527002016051:ios:ba33857a0b05150023c646',
    messagingSenderId: '527002016051',
    projectId: 'elevate-988ab',
    storageBucket: 'elevate-988ab.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5KoAdaag1WZcFPsulPMHpNtu0CFAI58U',
    appId: '1:527002016051:ios:ba33857a0b05150023c646',
    messagingSenderId: '527002016051',
    projectId: 'elevate-988ab',
    storageBucket: 'elevate-988ab.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdKxOVOLhqByLTbTQQxW8Ae3m8hELBu-Q',
    appId: '1:527002016051:web:c7c42129d61f2c9923c646',
    messagingSenderId: '527002016051',
    projectId: 'elevate-988ab',
    authDomain: 'elevate-988ab.firebaseapp.com',
    storageBucket: 'elevate-988ab.firebasestorage.app',
  );
}
