// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjqRJWRi6YObX62rBUAhVBWrLD-bSJxwA',
    appId: '1:985991355163:web:5f5eacc57328d3ed76d1be',
    messagingSenderId: '985991355163',
    projectId: 'elevate-app-a0e26',
    authDomain: 'elevate-app-a0e26.firebaseapp.com',
    storageBucket: 'elevate-app-a0e26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3Iq3WBeYq7HVrxj7JwWTzVTukX4aty8',
    appId: '1:985991355163:android:0dc6b4f8f5d045be76d1be',
    messagingSenderId: '985991355163',
    projectId: 'elevate-app-a0e26',
    storageBucket: 'elevate-app-a0e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFeUfVSHDSAnwU-ZUlML_ojKfipRKiYs',
    appId: '1:985991355163:ios:d3527aab4f36571f76d1be',
    messagingSenderId: '985991355163',
    projectId: 'elevate-app-a0e26',
    storageBucket: 'elevate-app-a0e26.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFeUfVSHDSAnwU-ZUlML_ojKfipRKiYs',
    appId: '1:985991355163:ios:d3527aab4f36571f76d1be',
    messagingSenderId: '985991355163',
    projectId: 'elevate-app-a0e26',
    storageBucket: 'elevate-app-a0e26.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjqRJWRi6YObX62rBUAhVBWrLD-bSJxwA',
    appId: '1:985991355163:web:beb9ceb13b2968cc76d1be',
    messagingSenderId: '985991355163',
    projectId: 'elevate-app-a0e26',
    authDomain: 'elevate-app-a0e26.firebaseapp.com',
    storageBucket: 'elevate-app-a0e26.firebasestorage.app',
  );
}
