// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi9H8NpKrVSxMU3zjQz6rQ0eGStK_yN1g',
    appId: '1:522315674299:web:c6fe0853ae6fd725522f9e',
    messagingSenderId: '522315674299',
    projectId: 'elevate-app-e488e',
    authDomain: 'elevate-app-e488e.firebaseapp.com',
    storageBucket: 'elevate-app-e488e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbA1KtzlT1Zz6sXoqNCCYcmVFfV4qISnw',
    appId: '1:522315674299:android:687dbe760b9d197b522f9e',
    messagingSenderId: '522315674299',
    projectId: 'elevate-app-e488e',
    storageBucket: 'elevate-app-e488e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1aiteZhPeoKCEDRWsCZR9ZUKK5JtWvCc',
    appId: '1:522315674299:ios:af0f0befe91858f4522f9e',
    messagingSenderId: '522315674299',
    projectId: 'elevate-app-e488e',
    storageBucket: 'elevate-app-e488e.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1aiteZhPeoKCEDRWsCZR9ZUKK5JtWvCc',
    appId: '1:522315674299:ios:af0f0befe91858f4522f9e',
    messagingSenderId: '522315674299',
    projectId: 'elevate-app-e488e',
    storageBucket: 'elevate-app-e488e.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi9H8NpKrVSxMU3zjQz6rQ0eGStK_yN1g',
    appId: '1:522315674299:web:955cd74e56f1b16f522f9e',
    messagingSenderId: '522315674299',
    projectId: 'elevate-app-e488e',
    authDomain: 'elevate-app-e488e.firebaseapp.com',
    storageBucket: 'elevate-app-e488e.firebasestorage.app',
  );

}